use std::io::prelude::*;
use std::path::Path;

use super::{AmplitudeType, Order};

pub(crate) fn write_order_file(order: &Order, path: &Path) -> Result<(), std::io::Error> {
    let mut writer = std::io::BufWriter::new(std::fs::File::create(path)?);
    writeln!(
        writer,
        r#"# BLHA2 order automatically generated by pygs
InterfaceVersion BLHA2
IRregularisation CDR"#
    )?;
    writeln!(writer, "Model ufo:/{}", order.model.path.to_str().unwrap())?;
    for (option, value) in order.options.iter() {
        writeln!(writer, "{option} {value}")?;
    }
    for (coupling, value) in order.coupling_orders.iter() {
        writeln!(writer, "CouplingPower {coupling} {}", value)?;
    }
    for s in order.subprocesses.iter() {
        writeln!(writer, "AmplitudeType {}", s.amplitude_type)?;
        writeln!(
            writer,
            "{} -> {}",
            s.incoming_pdg
                .iter()
                .map(|i| i.to_string())
                .collect::<Vec<_>>()
                .join(" "),
            s.outgoing_pdg
                .iter()
                .map(|i| i.to_string())
                .collect::<Vec<_>>()
                .join(" ")
        )?;
    }
    Ok(())
}
